const menu = [
  {
    id: 1,
    title: "French Toast",
    category: "Breakfast",
    price: "10.99",
    img: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2008/3/26/0/IE0309_French-Toast.jpg.rend.hgtvcom.616.462.suffix/1431730431340.jpeg",
    desc: "All happiness depends on a leisurely breakfast. One of the nicest things about life is the way.",
  },
  {
    id: 2,
    title: "Chicken Noddle",
    category: "Dinner",
    price: "35.99",
    img: "https://www.allrecipes.com/thmb/jOofJqYckYDfxlIMyCBMNJ3wz0I=/2000x2000/filters:no_upscale()/26460-quick-and-easy-chicken-noodle-soup-allrecipes-1x1-1-b88125437574471db3e114c40bc6928e.jpg",
    desc: "My weaknesses have always been food and men, in that order. One of the nicest things about life is the way we must .",
  },
  {
    id: 3,
    title: "Philippines breakfast",
    category: "Breakfast",
    price: "12.99",
    img: "http://cdn.cnn.com/cnnnext/dam/assets/220217215855-01-filipino-breakfast-longsilog.jpg",
    desc: "I watch cooking change the cook, just as it transforms the food. One of the nicest things about life is the way",
  },
  {
    id: 4,
    title: "Cabbage Soup",
    category: "Lunch",
    price: "40.99",
    img: "https://cdn.loveandlemons.com/wp-content/uploads/2021/03/cabbage-soup.jpg",
    desc: "I know once people get connected to real food, they never change back. One of the nicest things about life is the eating.",
  },
  {
    id: 5,
    title: "Cream of Celery Soup",
    category: "Dinner",
    price: "30.99",
    img: "https://www.simplyrecipes.com/thmb/6uzk-OdLB5l7V9X6kGNfsPCG9v8=/1757x1318/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2014__02__creamy-celery-soup-horiz-a-1800-068bb3f2bcd94ce8af3ea0cf41db51f8.jpg",
    desc: "I cook with wine. Sometimes I even add it to the food. One of the nicest things about life is the way we must eating",
  },
  {
    id: 6,
    title: "Singapor Breakfast",
    category: "Breakfast",
    price: "11.99",
    img: "http://cdn.cnn.com/cnnnext/dam/assets/190517113420-17-breakfast-around-the-world-eggs-and-sausage.jpg",
    desc: "The best comfort food will always be greens, cornbread, and fried chicken. One of the nicest things about life is the way ",
  },
  {
    id: 7,
    title: "Roasted Carrot Soup",
    category: "Lunch",
    price: "24.99",
    img: "https://img.delicious.com.au/KzfREL5B/del/2018/04/baked-sweet-potato-soup-with-blue-cheese-toast-77445-2.jpg",
    desc: "You don't need a silver fork to eat good food. One of the nicest things about life is the way we must regularly",
  },
  {
    id: 8,
    title: "Caramel Topped Ice Cream",
    category: "Dessert",
    price: "16.99",
    img: "https://storcpdkenticomedia.blob.core.windows.net/media/recipemanagementsystem/media/recipe-media-files/recipes/retail/x17/17244-caramel-topped-ice-cream-dessert-600x600.jpg?ext=.jpg",
    desc: "Life is uncertain. Eat dessert first. One of the nicest things about life is the way we must regularly stop whatever it is we eating",
  },
  {
    id: 9,
    title: "Cocktail",
    category: "Drinks",
    price: "8.99",
    img: "https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Singapore-sling-7ddad3e.jpg?quality=45&resize=960,872",
    desc: "Life is too short for self-hatred and celery sticks. One of the nicest things about life is the way",
  },
  {
    id: 10,
    title: "Arquivos Grenadine",
    category: "Drinks",
    price: "10.99",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfn24nVwBV0gjFuMuNaPYRW7WhuEaSL2zpelxUMeKAy0SJjh1lUU-NBhc55-0WFgXNdAc&usqp=CAU",
    desc: "People who love to eat are always the best people. One of the nicest things about life is the way we must regularly stop  ",
  },
];
export default menu;
